# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a348391d61aadd657a0a4f179d456088"
application_url = "https://lf-create-mechanics-procedures.trycloudflare.com"
embedded = true
name = "Product Review"
handle = "product-review-117"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://lf-create-mechanics-procedures.trycloudflare.com/auth/callback",
  "https://lf-create-mechanics-procedures.trycloudflare.com/auth/shopify/callback",
  "https://lf-create-mechanics-procedures.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
